server:
  port: ${PORT:0}
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  devtools:
    restart:
      enabled: true
  application:
    name: account-service
  boot:
    admin:
      client:
        url: http://localhost:8763
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone:
        http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id}:${random.value}}